In [1]:
import numpy as np
P0=[0.3,0.2,0.5]
P=[[0,2/3,1/3],[1/2,0,1/2],[1/2,1/2,0]]
n=6
for i in range(1,n+1):
    P0=np.multiply(P0,P)
    print("The %d -step probability distribution is"%i)
    print(P0)


The 1 -step probability distribution is
[[0.         0.13333333 0.16666667]
 [0.15       0.         0.25      ]
 [0.15       0.1        0.        ]]
The 2 -step probability distribution is
[[0.         0.08888889 0.05555556]
 [0.075      0.         0.125     ]
 [0.075      0.05       0.        ]]
The 3 -step probability distribution is
[[0.         0.05925926 0.01851852]
 [0.0375     0.         0.0625    ]
 [0.0375     0.025      0.        ]]
The 4 -step probability distribution is
[[0.         0.03950617 0.00617284]
 [0.01875    0.         0.03125   ]
 [0.01875    0.0125     0.        ]]
The 5 -step probability distribution is
[[0.         0.02633745 0.00205761]
 [0.009375   0.         0.015625  ]
 [0.009375   0.00625    0.        ]]
The 6 -step probability distribution is
[[0.         0.0175583  0.00068587]
 [0.0046875  0.         0.0078125 ]
 [0.0046875  0.003125   0.        ]]
